export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const SEARCH_ADDRESS_LIST = 'SEARCH_ADDRESS_LIST';
export const SET_QUOTE_DETAIL = 'SET_QUOTE_DETAIL'; 
export const SET_PAGE_LOADER = 'SET_PAGE_LOADER';
export const SET_PREV_ROUTE_PATH = 'SET_PREV_ROUTE_PATH';
export const GET_USER_DETAIL='GET_USER_DETAIL'
export const CARD_DETAIL='CARD_DETAIL'